# Travis-CI Build for OpenRA
# see travis-ci.org for details

# Mono/.NET are not officially supported. The following is a workaround.
language: c

# Make sure build dependencies are installed.
install:
 - sudo apt-get install mono-gmcs cli-common-dev libsdl1.2debian libgl1-mesa-glx libopenal1 libfreetype6 dpkg rpm nsis markdown

# Run the build script
# call RALint to check for YAML errors
# Test run the packaging scripts for all platforms
script:
 - make all
 - make test
 - cd packaging && mkdir temp &&./package-all.sh travis-build temp

# Only watch the development branch.
branches:
 only:
   - bleed

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
